#if !canImport(ObjectiveC)
import XCTest

extension SwiftStepicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftStepicTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftStepicTests.__allTests__SwiftStepicTests),
    ]
}
#endif
